Repository intelligent-machine-learning/dlrover, pull requests merged in 2024-12, with the labels that each got.

#1367 Fix event action consuming.
  dlrover/python/diagnosis/common/diagnosis_action.py
  dlrover/python/diagnosis/inferencechain/inference_chain.py
  dlrover/python/master/elastic_training/net_topology.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/tests/test_diagnosis.py
  dlrover/python/tests/test_job_manager.py
Labels: bug

#1369 Fix/Enhance DiagnosisAction using.
  dlrover/python/diagnosis/common/diagnosis_action.py
  dlrover/python/elastic_agent/master_client.py
  dlrover/python/tests/test_diagnosis.py
  dlrover/python/tests/test_master_client.py
Labels: bug, enhancement

#1347 correct log and complete ut for error_monitor
  dlrover/python/master/monitor/error_monitor.py
  dlrover/python/tests/test_error_monitor.py
Labels: enhancement

#1370 Add document for diagnosis's design.
  .github/workflows/main.yml
  docs/design/proactive-diagnosis.md
  docs/figures/diagnosis_agent_arc.png
  docs/figures/diagnosis_arc.png
  docs/figures/diagnosis_manager_arc.png
  docs/figures/training_hang_detection.png
Labels: documentation

#1376 Fix node event process issue.
  dlrover/python/master/node/dist_job_manager.py
Labels: bug

#1168 Add sockct close v2
  dlrover/python/common/multi_process.py
Labels: enhancement, wip

#1408 Optimize status flow validation
  dlrover/python/master/node/status_flow.py
  dlrover/python/tests/test_job_manager.py
Labels: bug
