Repository intelligent-machine-learning/dlrover, pull requests merged in 2024-05, with the labels that each got.

#1101 optimize master pod retrieving
  dlrover/python/common/env_utils.py
  dlrover/python/master/scaler/pod_scaler.py
  dlrover/python/tests/test_k8s_util.py
  dlrover/python/tests/test_pod_scaler.py
  dlrover/python/tests/test_utils.py
  dlrover/python/util/k8s_util.py
Labels: enhancement, dlrover-master

#1100 Set the deletion strategy and timeout in the checkpointers.
  codecov.yml
  dlrover/python/common/constants.py
  dlrover/python/common/storage.py
  dlrover/python/elastic_agent/torch/ckpt_saver.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/master/scaler/pod_scaler.py
  dlrover/python/tests/test_elastic_training_agent.py
  dlrover/python/tests/test_storage.py
  dlrover/trainer/tests/torch/ddp_checkpointer_test.py
  dlrover/trainer/torch/flash_checkpoint/ddp.py
  dlrover/trainer/torch/flash_checkpoint/deepspeed.py
  dlrover/trainer/torch/flash_checkpoint/deepspeed_engine.py
  dlrover/trainer/torch/flash_checkpoint/engine.py
  dlrover/trainer/torch/flash_checkpoint/fsdp.py
  dlrover/trainer/torch/flash_checkpoint/fsdp_engine.py
  dlrover/trainer/torch/flash_checkpoint/full_ckpt_engine.py
  dlrover/trainer/torch/flash_checkpoint/megatron.py
  dlrover/trainer/torch/flash_checkpoint/megatron_dist_ckpt.py
  dlrover/trainer/torch/flash_checkpoint/megatron_engine.py
  docs/blogs/flash_checkpoint.md
  docs/blogs/flash_checkpoint_cn.md
Labels: flash checkpoint

#1124 add log for pod event watcher
  dlrover/python/master/watcher/k8s_watcher.py
Labels: enhancement

#1125 fix pod event converting invocation
  dlrover/python/master/watcher/k8s_watcher.py
Labels: bug

#1126 optimize MODIFIED event with deletion info
  dlrover/python/master/watcher/k8s_watcher.py
  dlrover/python/tests/test_k8s_watcher.py
  dlrover/python/tests/test_utils.py
Labels: enhancement

#1131 optimize master retrieving
  dlrover/python/master/scaler/pod_scaler.py
Labels: enhancement

#1139 collect error content
  dlrover/python/common/constants.py
  dlrover/python/master/servicer.py
Labels: enhancement
