Repository intelligent-machine-learning/dlrover, pull requests merged in 2024-11, with the labels that each got.

#1315 Refactor node event report and report succeeded.
  dlrover/python/common/constants.py
  dlrover/python/common/grpc.py
  dlrover/python/common/node.py
  dlrover/python/elastic_agent/master_client.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/node/job_manager.py
  dlrover/python/master/servicer.py
  dlrover/python/master/watcher/base_watcher.py
  dlrover/python/tests/test_job_manager.py
  dlrover/python/tests/test_master_client.py
  dlrover/python/tests/test_node.py
  dlrover/python/tests/test_servicer.py
  dlrover/trainer/tests/torch/node_check_test.py
  dlrover/trainer/torch/node_check/utils.py
  dlrover/trainer/worker/tf_ray_worker.py
Labels: enhancement

#1317 Fix empty node issue after master failover
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/tests/test_job_manager.py
Labels: bug

#1328 Function using/naming optimized based on job context.
  dlrover/python/master/node/ps.py
  dlrover/python/master/node/training_node.py
  dlrover/python/master/node/worker.py
Labels: enhancement

#1329 Skip heartbeat timeout for failed and exited worker
  dlrover/python/common/constants.py
  dlrover/python/common/node.py
  dlrover/python/elastic_agent/master_client.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/tests/test_job_manager.py
  dlrover/python/tests/test_node.py
  dlrover/python/tests/test_servicer.py
Labels: enhancement

#1330 Delete pod when list pod already succeeded.
  dlrover/python/master/watcher/k8s_watcher.py
  dlrover/python/tests/test_k8s_watcher.py
Labels: enhancement

#1334 Fix diagnosis agent action consuming
  dlrover/python/elastic_agent/context.py
  dlrover/python/elastic_agent/diagnosis/diagnosis_agent.py
  dlrover/python/master/node/job_context.py
  dlrover/python/tests/test_diagnosis_agent.py
Labels: bug

#1341 Skip memory limitation for gpu type node relaunch operation.
  dlrover/python/common/node.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/node/training_node.py
  dlrover/python/master/resource/job.py
  dlrover/python/tests/test_node.py
  dlrover/python/tests/test_resource_optimizer.py
Labels: bug, enhancement

#1346 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: dev issue

#1353 Fix known issue
  dlrover/python/diagnosis/common/diagnosis_action.py
  dlrover/python/diagnosis/datacollector/xpu_timer_metric_collector.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/resource/job.py
  dlrover/python/tests/test_common_util.py
  dlrover/python/tests/test_diagnosis.py
  dlrover/python/tests/test_diagnosis_data_collector.py
  dlrover/python/tests/test_resource_optimizer.py
  dlrover/python/util/common_util.py
Labels: bug, enhancement

#1354 Fix node id iterator initiation.
  dlrover/python/common/env_utils.py
  dlrover/python/diagnosis/inferencechain/inferenceoperator/observer/check_training_hang_operator.py
  dlrover/python/master/dist_master.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/node/ps.py
  dlrover/python/master/node/training_node.py
  dlrover/python/master/node/worker.py
Labels: bug

#1356 Fix rank iter implement.
  dlrover/python/master/node/training_node.py
Labels: bug, wip

#1357 Fix unexpected heartbeat issue after worker relaunching.
  dlrover/python/common/node.py
  dlrover/python/elastic_agent/monitor/resource.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/tests/test_node.py
Labels: bug, enhancement

#1322 feat: generate pyi files for protobuf definitions
  dlrover/proto/protobuf_3_20_3/brain_pb2.pyi
  dlrover/proto/protobuf_3_20_3/elastic_training_pb2.pyi
  dlrover/proto/protobuf_4_25_3/brain_pb2.pyi
  dlrover/proto/protobuf_4_25_3/elastic_training_pb2.pyi
  scripts/build_proto.sh
Labels: enhancement, dev issue

#1361 Fix socket client using(before socket server creation).
  dlrover/python/common/multi_process.py
  dlrover/trainer/torch/flash_checkpoint/engine.py
Labels: bug

#1355 Remove duplicated implements(diagnosis part).
  dlrover/python/diagnosis/common/diagnosis_action.py
  dlrover/python/master/diagnosis/diagnosis.py
  dlrover/python/master/diagnosis/diagnosis_data_manager.py
  dlrover/python/master/dist_master.py
  dlrover/python/master/servicer.py
  dlrover/python/tests/test_servicer.py
  dlrover/python/util/time_util.py
Labels: enhancement, wip

#1365 optimize diagnosing in job manager
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/tests/test_job_manager.py
Labels: enhancement

#1364 Enhance 'build_proto.sh' script.
  scripts/build_proto.sh
Labels: enhancement
