Repository intelligent-machine-learning/dlrover, pull requests merged in 2024-07, with the labels that each got.

#1177 fix ShardCkptReplicaManager when replica = 0
  dlrover/trainer/tests/torch/checkpoint_backup_test.py
  dlrover/trainer/torch/flash_checkpoint/replica.py
Labels: bug

#1182 Multi issue fixed.
  dlrover/python/elastic_agent/torch/ckpt_saver.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/master/elastic_training/rdzv_manager.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/tests/test_file_util.py
  dlrover/python/tests/test_job_manager.py
  dlrover/python/tests/test_rdzv_manager.py
  dlrover/python/tests/test_utils.py
  dlrover/python/util/file_util.py
Labels: enhancement

#1184 Unify job manager's stop status field
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/node/job_manager.py
  dlrover/python/master/node/local_job_manager.py
  dlrover/python/tests/test_job_manager.py
Labels: enhancement

#1186 fix exception when plan is none
  dlrover/python/master/node/job_auto_scaler.py
  dlrover/python/tests/test_job_auto_scaler.py
Labels: bug

#1189 Fix heart beat for concurency.
  dlrover/python/elastic_agent/master_client.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/stats/stats_backend.py
  dlrover/python/tests/test_elastic_training_agent.py
  dlrover/python/tests/test_elasticjob_scaler.py
  dlrover/python/tests/test_job_manager.py
  dlrover/python/tests/test_sharding_client.py
  dlrover/python/tests/test_task_manager.py
  dlrover/python/tests/test_utils.py
  dlrover/python/util/state/store_mananger.py
Labels: bug

#1192 Fix log file bugs
  dlrover/python/elastic_agent/torch/training.py
Labels: bug

#1193 optimize elastic-run logging
  dlrover/trainer/torch/elastic_run.py
Labels: enhancement

#1194 optimize heartbeat logging
  dlrover/python/elastic_agent/monitor/training.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/master/node/dist_job_manager.py
Labels: enhancement

#1197 fix time type issue
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/tests/test_job_manager.py
Labels: bug

#1198 Add try except for getting dead node.
  dlrover/python/master/node/dist_job_manager.py
Labels: enhancement

#1200 Fix heartbeat when there is node relaunched.
  dlrover/python/common/node.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/tests/test_job_manager.py
Labels: bug

#1196 Add failure reporting for async ckpt saver.
  dlrover/python/common/error.py
  dlrover/python/elastic_agent/torch/ckpt_saver.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/tests/test_ckpt_saver.py
  dlrover/python/tests/test_elastic_training_agent.py
Labels: enhancement

#1204 Increase heartbeat timeout
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/tests/test_job_manager.py
Labels: enhancement

#1206 Support optional debug log level.
  dlrover/python/common/constants.py
  dlrover/python/common/log.py
  dlrover/python/tests/test_log.py
  scripts/ci_install.sh
Labels: enhancement, dlrover-master

#1205 Enhancement of hccl port config resolution.
  dlrover/python/common/constants.py
  dlrover/python/common/env_utils.py
  dlrover/python/common/grpc.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/tests/test_elastic_training_agent.py
  dlrover/python/tests/test_grpc_utils.py
Labels: enhancement

#1207 Optimize node status from pod phase.
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/watcher/k8s_watcher.py
  dlrover/python/tests/test_k8s_watcher.py
  dlrover/python/tests/test_utils.py
Labels: enhancement, dlrover-master

#1209 Keep conflict processing when env set
  dlrover/python/common/grpc.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/tests/test_elastic_training_agent.py
Labels: enhancement

#1211 Fix user-agent issue.
  dlrover/python/scheduler/kubernetes.py
  dlrover/python/tests/test_k8s_utils.py
Labels: bug

#1173 Pod scaler enhancement: support concurrent creation
  dlrover/python/master/scaler/pod_scaler.py
  dlrover/python/tests/test_pod_scaler.py
Labels: enhancement

#1213 Add signal timeout for 'stop_workers'
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/tests/test_elastic_training_agent.py
Labels: enhancement

#1216 Optimize logging in rdzf manager.
  dlrover/python/master/elastic_training/rdzv_manager.py
  dlrover/python/master/scaler/pod_scaler.py
  dlrover/python/tests/test_rdzv_manager.py
Labels: enhancement

#1217 Fix scaler async execution.
  dlrover/python/master/scaler/pod_scaler.py
Labels: bug
