Repository intelligent-machine-learning/dlrover, pull requests merged in 2025-01, with the labels that each got.

#1419 Fix known issue of 'diagnosis_agent'.
  dlrover/python/diagnosis/common/constants.py
  dlrover/python/elastic_agent/diagnosis/diagnosis_agent.py
  dlrover/python/elastic_agent/monitor/training.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/tests/test_diagnosis_agent.py
Labels: bug

#1420 if node failed and exited, need relaunch on heartbeat timeout
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/tests/test_job_manager.py
Labels: enhancement

#1340 fix a bug in infer method
  dlrover/python/diagnosis/inferencechain/inference_chain.py
Labels: investigating

#1427 Enhance ut performance
  dlrover/python/common/constants.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/tests/test_diagnosis.py
  dlrover/python/tests/test_diagnosis_manager.py
  dlrover/python/tests/test_elastic_training_agent.py
  dlrover/python/tests/test_pod_scaler.py
  dlrover/python/tests/test_worker_manager.py
Labels: enhancement

#1431 Add arguments support and doc.
  dlrover/go/operator/pkg/controllers/elasticjob_controller.go
  dlrover/go/operator/pkg/controllers/master/master.go
  dlrover/go/operator/pkg/controllers/master/master_test.go
  dlrover/python/master/args.py
  dlrover/python/tests/test_args.py
  dlrover/trainer/torch/elastic_run.py
  docs/deployment/argument.md
Labels: documentation, enhancement

#1439 reduce check fault timeout and check straggler timeout to 1 sec
  dlrover/python/common/constants.py
Labels: enhancement

#1442 Refactor client's node-check invocation timeout default value.
  dlrover/python/common/constants.py
  dlrover/python/elastic_agent/master_client.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/tests/test_elastic_training_agent.py
Labels: enhancement

#1447 Fix network check status report issue.
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/tests/test_elastic_training_agent.py
Labels: bug

#1450 Refactor failed node counter.
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/node/event_callback.py
  dlrover/python/master/node/job_context.py
  dlrover/python/tests/test_event_callback.py
  dlrover/python/tests/test_job_manager.py
Labels: bug

#1452 update homepage for latest news.
  README.md
Labels: documentation

#1429 Support http communication implement for DLRover Master and Agent.
  .github/actions/dlrover-system-test-criteo-deeprec/action.yaml
  .github/actions/dlrover-system-test-deepfm/action.yaml
  .github/actions/dlrover-system-test-tf2/action.yaml
  dlrover/python/brain/client.py
  dlrover/python/common/comm.py
  dlrover/python/common/constants.py
  dlrover/python/common/global_context.py
  dlrover/python/common/http_server.py
  dlrover/python/common/log.py
  dlrover/python/common/node.py
  dlrover/python/elastic_agent/config/paral_config_tuner.py
  dlrover/python/elastic_agent/master_client.py
  dlrover/python/elastic_agent/monitor/resource.py
  dlrover/python/elastic_agent/sharding/client.py
  dlrover/python/elastic_agent/tensorflow/hooks.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/master/args.py
  dlrover/python/master/dist_master.py
  dlrover/python/master/hyperparams/simple_strategy_generator.py
  dlrover/python/master/local_master.py
  dlrover/python/master/master.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/node/local_job_manager.py
  dlrover/python/master/scaler/pod_scaler.py
  dlrover/python/master/servicer.py
  dlrover/python/master/shard/task_manager.py
  dlrover/python/master/stats/job_collector.py
  dlrover/python/master/stats/reporter.py
  dlrover/python/tests/test_agent_config_tuner.py
  dlrover/python/tests/test_agent_monitor.py
  dlrover/python/tests/test_args.py
  dlrover/python/tests/test_common_util.py
  dlrover/python/tests/test_grpc_utils.py
  dlrover/python/tests/test_http_server.py
  dlrover/python/tests/test_job_manager.py
  dlrover/python/tests/test_master_client.py
  dlrover/python/tests/test_servicer.py
  dlrover/python/tests/test_sharding_client.py
  dlrover/python/tests/test_strategy_generator.py
  dlrover/python/tests/test_task_manager.py
  dlrover/python/tests/test_utils.py
  dlrover/python/util/common_util.py
  dlrover/trainer/tests/torch/checkpoint_egine_test.py
  dlrover/trainer/tests/torch/elastic_dataloader_test.py
  dlrover/trainer/tests/torch/elastic_test.py
  dlrover/trainer/tests/torch/fsdp_ckpt_test.py
  dlrover/trainer/torch/elastic_run.py
  docker/ci.dockerfile
  docs/deployment/argument.md
  go/elasticjob/pkg/controllers/master/master.go
  go/elasticjob/pkg/controllers/master/master_test.go
  scripts/ci_install.sh
Labels: feature
