Repository intelligent-machine-learning/dlrover, pull requests merged in 2025-08, with the labels that each got.

#1600 Update ci.
  .github/workflows/publish_pypi.yml
  docker/release/master.dockerfile
Labels: dev issue

#1602 Add node group failover
  dlrover/python/common/constants.py
  dlrover/python/common/global_context.py
  dlrover/python/common/node.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/node/job_context.py
  dlrover/python/master/node/job_manager.py
  dlrover/python/master/node/training_node.py
  dlrover/python/master/node/worker.py
  dlrover/python/master/scaler/pod_scaler.py
  dlrover/python/master/watcher/k8s_watcher.py
  dlrover/python/tests/test_job_manager.py
  dlrover/python/tests/test_node.py
  dlrover/python/tests/test_worker_manager.py
Labels: feature

#1604 Fix unexpected rdzv complete which caused abnormal node check execution.
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/master/elastic_training/rdzv_manager.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/scaler/pod_scaler.py
  dlrover/python/master/servicer.py
  dlrover/python/tests/test_rdzv_manager.py
Labels: bug

#1606 UT fix.
  dlrover/python/tests/test_elastic_training_agent.py
  dlrover/python/tests/test_metric_monitor.py
Labels: dev issue

#1617 Handle empty opt plan
  codecov.yml
  dlrover/python/master/resource/brain_optimizer.py
  dlrover/python/tests/test_resource_optimizer.py
Labels: enhancement
