Repository intelligent-machine-learning/dlrover, pull requests merged in 2025-09, with the labels that each got.

#1625 [Unified] New VeRL example.
  dlrover/python/tests/test_metric_monitor.py
  dlrover/python/unified/api/builder/base.py
  dlrover/python/unified/api/runtime/rpc_helper.py
  dlrover/python/unified/backend/rl/__init__.py
  dlrover/python/unified/backend/rl/remote_call.py
  dlrover/python/unified/backend/rl/trainer.py
  dlrover/python/unified/backend/rl/worker.py
  dlrover/python/unified/tests/api/test_builder.py
  dlrover/python/unified/tests/api/test_runtime.py
  dlrover/python/unified/tests/backend/rl/__init__.py
  dlrover/python/unified/tests/backend/rl/classes.py
  dlrover/python/unified/tests/backend/rl/test_trainer.py
  dlrover/python/unified/tests/backend/rl/test_workload.py
  dlrover/python/unified/tests/util/test_actor_helper.py
  dlrover/python/unified/util/actor_helper.py
  dlrover/python/unified/util/async_helper.py
  docs/tutorial/unified/03-multi-role-training.md
  docs/tutorial/unified/03b-multi-role-training-verl.md
  docs/tutorial/unified/README.md
  examples/unified/rl/verl/base/__init__.py
  examples/unified/rl/verl/base/decorator.py
  examples/unified/rl/verl/base/megatron_workers.py
  examples/unified/rl/verl/base/worker.py
  examples/unified/rl/verl/main.py
  examples/unified/rl/verl/ppo/__init__.py
  examples/unified/rl/verl/ppo/main.py
  examples/unified/rl/verl/ppo/ppo_trainer.py
  examples/unified/rl/verl/run.sh
  examples/unified/rl/verl/util.py
  examples/unified/rl/verl/workers.py
Labels: documentation, example

#1629 Enhancement 20250904
  dlrover/python/unified/controller/schedule/scaler.py
  dlrover/python/unified/tests/controller/test_scaler.py
  dlrover/python/unified/tests/util/test_registry.py
  dlrover/python/unified/util/auto_registry.py
Labels: enhancement

#1632 Add token validation for server.
  dlrover/python/common/constants.py
  dlrover/python/common/env_utils.py
  dlrover/python/elastic_agent/master_client.py
  dlrover/python/master/node/job_manager.py
  dlrover/python/master/servicer.py
  dlrover/python/tests/test_servicer.py
Labels: enhancement

#1627 [Unified] Master failover
  dlrover/python/unified/api/runtime/rpc_helper.py
  dlrover/python/unified/backend/elastic/manager.py
  dlrover/python/unified/backend/elastic/master.py
  dlrover/python/unified/common/actor_base.py
  dlrover/python/unified/common/config.py
  dlrover/python/unified/common/constant.py
  dlrover/python/unified/common/enums.py
  dlrover/python/unified/controller/extension.py
  dlrover/python/unified/controller/manager.py
  dlrover/python/unified/controller/master.py
  dlrover/python/unified/controller/schedule/graph.py
  dlrover/python/unified/controller/schedule/scaler.py
  dlrover/python/unified/controller/state_backend.py
  dlrover/python/unified/tests/common/test_actor_base.py
  dlrover/python/unified/tests/conftest.py
  dlrover/python/unified/tests/controller/extension_test/node_relaunch.py
  dlrover/python/unified/tests/controller/test_manager.py
  dlrover/python/unified/tests/fixtures/example_jobs.py
  dlrover/python/unified/tests/fixtures/misc.py
  dlrover/python/unified/tests/util/test_extension_util.py
  dlrover/python/unified/tests/util/test_registry.py
  dlrover/python/unified/util/actor_helper.py
  dlrover/python/unified/util/auto_registry.py
  dlrover/python/unified/util/extension_util.py
  dlrover/python/unified/util/test_hooks.py
Labels: feature

#1631 [Unified] Rank-based GPU Selection
  codecov.yml
  dlrover/python/unified/backend/elastic/worker/worker.py
  dlrover/python/unified/common/actor_base.py
  dlrover/python/unified/common/config.py
  dlrover/python/unified/common/workload_desc.py
  dlrover/python/unified/controller/schedule/scheduler.py
  dlrover/python/unified/tests/backend/test_elastic.py
  dlrover/python/unified/tests/common/test_actor_base.py
  dlrover/python/unified/tests/common/test_workload_desc.py
  dlrover/python/unified/util/extension_util.py
  docs/design/unified-architecture.md
  docs/figures/unified/gpu_allocation_strategy-A,B share gpu.png
  docs/figures/unified/gpu_allocation_strategy-A,B share node.png
  docs/tutorial/unified/01-get-start.md
Labels: enhancement

#1628 Skip container with empty cpu or mem when calculate node resources from yaml
  dlrover/python/common/global_context.py
  dlrover/python/common/node.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/node/event_callback.py
  dlrover/python/master/node/training_node.py
  dlrover/python/master/scaler/pod_scaler.py
  dlrover/python/master/watcher/k8s_watcher.py
  dlrover/python/tests/test_job_manager.py
  dlrover/python/tests/test_k8s_watcher.py
Labels: bug

#1633 Fix manager instance issue.
  dlrover/python/unified/controller/manager.py
  dlrover/python/unified/tests/controller/test_manager.py
Labels: bug

#1635 Optimize node relaunch impl.
  dlrover/python/master/diagnosis/diagnosis_master.py
  dlrover/python/unified/controller/extension.py
  dlrover/python/unified/controller/manager.py
  dlrover/python/unified/tests/controller/test_manager.py
Labels: enhancement

#1636 [Unified] Failover refactor
  dlrover/python/unified/api/builder/base.py
  dlrover/python/unified/api/builder/rl.py
  dlrover/python/unified/backend/common/base_worker.py
  dlrover/python/unified/backend/elastic/manager.py
  dlrover/python/unified/backend/elastic/master.py
  dlrover/python/unified/backend/elastic/remote_call.py
  dlrover/python/unified/backend/elastic/worker/worker.py
  dlrover/python/unified/common/actor_base.py
  dlrover/python/unified/common/enums.py
  dlrover/python/unified/common/workload_desc.py
  dlrover/python/unified/controller/api.py
  dlrover/python/unified/controller/events.py
  dlrover/python/unified/controller/manager.py
  dlrover/python/unified/controller/master.py
  dlrover/python/unified/controller/remote_call.py
  dlrover/python/unified/controller/schedule/graph.py
  dlrover/python/unified/controller/schedule/scheduler.py
  dlrover/python/unified/tests/api/test_runtime.py
  dlrover/python/unified/tests/backend/test_common.py
  dlrover/python/unified/tests/controller/test_manager.py
  dlrover/python/unified/tests/controller/test_schedule.py
  dlrover/python/unified/tests/integration_test/rl_mock/classes.py
  dlrover/python/unified/tests/integration_test/rl_mock/remote_call.py
  dlrover/python/unified/tests/integration_test/rl_mock/training_test.py
  dlrover/python/unified/util/decorators.py
  docs/design/unified-architecture.md
  docs/develop/unified_failover_design.md
Labels: enhancement

#1638 Fix 20250916
  dlrover/python/master/servicer.py
  dlrover/python/master/watcher/k8s_watcher.py
Labels: enhancement

#1637 [Unified] Parse options from envs when submit job.
  dlrover/python/unified/api/builder/base.py
  dlrover/python/unified/common/config.py
  dlrover/python/unified/common/constant.py
  dlrover/python/unified/driver/main.py
  dlrover/python/unified/tests/api/test_builder.py
  dlrover/python/unified/tests/driver/test_driver.py
  dlrover/python/unified/util/config_util.py
  docs/design/unified_failover_design.md
  docs/tutorial/unified/02-unified-api-guide.md
Labels: enhancement

#1639 [Unified] Failover refactor
  dlrover/python/unified/backend/elastic/master.py
  dlrover/python/unified/common/actor_base.py
  dlrover/python/unified/common/workload_desc.py
  dlrover/python/unified/controller/events.py
  dlrover/python/unified/controller/manager.py
  dlrover/python/unified/controller/master.py
  dlrover/python/unified/controller/schedule/graph.py
  dlrover/python/unified/tests/controller/extension_test/node_relaunch.py
  dlrover/python/unified/tests/controller/test_manager.py
  dlrover/python/unified/tests/util/test_actor_helper.py
  dlrover/python/unified/tests/util/test_decorators.py
  dlrover/python/unified/util/actor_helper.py
  dlrover/python/unified/util/decorators.py
Labels: enhancement

#1641 Limit device check execution on node start.
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/tests/test_elastic_training_agent.py
  dlrover/python/unified/api/builder/base.py
  examples/unified/elastic/nanogpt/train.py
Labels: enhancement

#1642 [UNIFIED] Support master-worker isolation scheduling.
  dlrover/python/unified/common/config.py
  dlrover/python/unified/controller/master.py
  dlrover/python/unified/controller/schedule/scheduler.py
  dlrover/python/unified/tests/integration_test/elastic_training_test.py
  docs/tutorial/unified/02-unified-api-guide.md
Labels: feature
