Repository intelligent-machine-learning/dlrover, pull requests merged in 2025-05, with the labels that each got.

#1536 Fix job manager endlessly waiting when pod reported SUCCEEDED_EXITED but DELETED when terminating timeout
  dlrover/python/common/metric/monitor.py
  dlrover/python/common/node.py
  dlrover/python/master/dist_master.py
  dlrover/python/master/node/training_node.py
  dlrover/python/master/node/worker.py
  dlrover/python/master/servicer.py
  dlrover/python/tests/test_node.py
  dlrover/python/tests/test_worker_manager.py
Labels: bug

#1543 Fix action init error
  dlrover/python/diagnosis/common/diagnosis_action.py
Labels: bug

#1544 fix case: has node relaunched after master restart
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/tests/test_job_manager.py
Labels: bug

#1550 Fix node exit reason.
  dlrover/python/common/constants.py
  dlrover/python/master/watcher/k8s_watcher.py
  dlrover/python/tests/test_k8s_watcher.py
  dlrover/python/tests/test_node.py
Labels: bug

#1513 Refactor diagnosis system: convert inference chain implementation to diagnostician implementation.
  dlrover/python/common/constants.py
  dlrover/python/diagnosis/common/constants.py
  dlrover/python/diagnosis/common/diagnosis_manager.py
  dlrover/python/diagnosis/common/diagnostician.py
  dlrover/python/diagnosis/datacollector/data_collector.py
  dlrover/python/diagnosis/datacollector/resource_collector.py
  dlrover/python/diagnosis/datacollector/xpu_timer_metric_collector.py
  dlrover/python/diagnosis/diagnostician/resource_collect_error_diagnostician.py
  dlrover/python/diagnosis/inferencechain/inferenceoperator/observer/check_failure_node_operator.py
  dlrover/python/diagnosis/inferencechain/inferenceoperator/observer/check_resource_collection_operator.py
  dlrover/python/diagnosis/inferencechain/inferenceoperator/observer/metrics_collection_operator.py
  dlrover/python/diagnosis/inferencechain/inferenceoperator/observer/resource_collection_operator.py
  dlrover/python/diagnosis/inferencechain/inferenceoperator/operator.py
  dlrover/python/diagnosis/inferencechain/inferenceoperator/resolver/resolve_gpu_errors_operator.py
  dlrover/python/elastic_agent/context.py
  dlrover/python/elastic_agent/diagnosis/diagnosis_agent.py
  dlrover/python/tests/test_diagnosis_agent.py
  dlrover/python/tests/test_diagnosis_data_collector.py
  dlrover/python/tests/test_diagnosis_manager.py
  dlrover/python/tests/test_diagnostician.py
  dlrover/python/tests/test_elastic_training_agent.py
  dlrover/python/tests/test_function_util.py
  dlrover/python/tests/test_inference.py
  dlrover/python/tests/test_inference_chain.py
  dlrover/python/util/function_util.py
Labels: dev issue

#1552 Fix/refactor controller
  go/elasticjob/pkg/controllers/elasticjob_controller.go
Labels: enhancement

#1531 Fix test_elastic_training_agent.py for torch version 2.4 and above.
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/tests/test_elastic_training_agent.py
Labels: enhancement
