Repository intelligent-machine-learning/dlrover, pull requests merged in 2025-03, with the labels that each got.

#1480 Monitor/Reporter refactoring.
  dlrover/python/common/constants.py
  dlrover/python/common/event/reporter.py
  dlrover/python/diagnosis/inferencechain/inferenceoperator/resolver/resolve_gpu_errors_operator.py
  dlrover/python/diagnosis/inferencechain/inferenceoperator/resolver/resolve_training_hang_operator.py
  dlrover/python/elastic_agent/torch/ckpt_saver.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/master/diagnosis/diagnosis_manager.py
  dlrover/python/master/dist_master.py
  dlrover/python/master/elastic_training/rdzv_manager.py
  dlrover/python/master/local_master.py
  dlrover/python/master/main.py
  dlrover/python/master/monitor/error_monitor.py
  dlrover/python/master/monitor/perf_monitor.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/node/event_callback.py
  dlrover/python/master/node/job_auto_scaler.py
  dlrover/python/master/node/job_manager.py
  dlrover/python/master/node/local_job_manager.py
  dlrover/python/master/scaler/pod_scaler.py
  dlrover/python/master/servicer.py
  dlrover/python/master/shard/task_manager.py
  dlrover/python/master/stats/job_collector.py
  dlrover/python/tests/test_elastic_training_agent.py
  dlrover/python/tests/test_error_monitor.py
  dlrover/python/tests/test_inference.py
  dlrover/python/tests/test_inference_chain.py
  dlrover/python/tests/test_inference_coordination.py
  dlrover/python/tests/test_job_auto_scaler.py
  dlrover/python/tests/test_job_manager.py
  dlrover/python/tests/test_pod_scaler.py
  dlrover/python/tests/test_rdzv_manager.py
  dlrover/python/tests/test_reporter.py
  dlrover/python/tests/test_servicer.py
  dlrover/python/tests/test_speed_monitor.py
  dlrover/python/tests/test_stats_collector.py
  dlrover/python/tests/test_sync_service.py
  dlrover/python/tests/test_utils.py
Labels: enhancement

#1491 Add reporter init
  dlrover/python/common/event/reporter.py
  dlrover/python/tests/test_reporter.py
Labels: enhancement

#1493 Logging enhancement for 'relaunch' procedure.
  dlrover/python/common/node.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/node/event_callback.py
  dlrover/python/tests/test_node.py
Labels: enhancement

#1497 Fix insufficient judgement.
  dlrover/python/master/node/worker.py
  dlrover/python/tests/test_worker_manager.py
Labels: bug

#1498 optimize training_events logs
  dlrover/python/common/event/reporter.py
  dlrover/python/elastic_agent/diagnosis/diagnosis_agent.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/master/dist_master.py
  dlrover/python/master/elastic_training/rdzv_manager.py
  dlrover/python/tests/test_elastic_training_agent.py
  dlrover/python/tests/test_rdzv_manager.py
  dlrover/python/tests/test_reporter.py
  dlrover/python/tests/test_training_events.py
  dlrover/python/training_event/config.py
  dlrover/python/training_event/predefined/_dlrover.py
Labels: enhancement

#1499 Add a new debug parameter 'task_process_timeout' arg
  dlrover/python/common/global_context.py
  dlrover/python/master/args.py
  dlrover/python/master/dist_master.py
  dlrover/python/master/main.py
  dlrover/python/master/shard/task_manager.py
  dlrover/python/scheduler/job.py
  dlrover/python/scheduler/kubernetes.py
  dlrover/python/tests/test_args.py
Labels: dev issue

#1502 Avoid exception raising in reporter.
  dlrover/python/common/event/reporter.py
  dlrover/python/tests/test_function_util.py
  dlrover/python/tests/test_reporter.py
  dlrover/python/util/function_util.py
Labels: enhancement

#1505 Fix pre-check issue.
  dlrover/python/master/diagnosis/diagnosis_manager.py
  dlrover/python/master/dist_master.py
  dlrover/python/tests/test_diagnosis_manager.py
Labels: bug

#1475 Refactor diagnosis system
  dlrover/python/diagnosis/common/constants.py
  dlrover/python/diagnosis/common/diagnosis_manager.py
  dlrover/python/diagnosis/common/diagnostician.py
  dlrover/python/diagnosis/diagnostician/__init__.py
  dlrover/python/diagnosis/diagnostician/failure_node_diagnostician.py
  dlrover/python/diagnosis/inferencechain/inferenceoperator/operator.py
  dlrover/python/elastic_agent/diagnosis/diagnosis_agent.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/master/diagnosis/diagnosis_master.py
  dlrover/python/master/dist_master.py
  dlrover/python/master/local_master.py
  dlrover/python/master/node/job_context.py
  dlrover/python/master/servicer.py
  dlrover/python/tests/test_diagnosis_manager.py
  dlrover/python/tests/test_diagnosis_master.py
  dlrover/python/tests/test_diagnostician.py
  dlrover/python/tests/test_global_context.py
  dlrover/python/tests/test_inference.py
  dlrover/python/tests/test_master.py
  dlrover/python/tests/test_servicer.py
  docs/design/proactive-diagnosis.md
  docs/figures/diagnosis_arc.png
  docs/figures/diagnosis_manager_arc.jpg
  docs/figures/diagnosis_manager_arc.png
Labels: dev issue
