Repository intelligent-machine-learning/dlrover, pull requests merged in 2025-02, with the labels that each got.

#1462 Rm master report event in training subprocess.
  dlrover/python/elastic_agent/torch/ckpt_saver.py
  dlrover/python/master/elastic_training/rdzv_manager.py
Labels: bug

#1463 Fix try-except when node-check failed.
  dlrover/python/elastic_agent/torch/training.py
Labels: bug

#1451 add Training event Exporter
  .gitignore
  dlrover/python/elastic_agent/torch/ckpt_saver.py
  dlrover/python/master/main.py
  dlrover/python/tests/test_ckpt_saver.py
  dlrover/python/tests/test_error_handler.py
  dlrover/python/tests/test_event_config.py
  dlrover/python/tests/test_event_emitter.py
  dlrover/python/tests/test_event_exporter.py
  dlrover/python/training_event/__init__.py
  dlrover/python/training_event/config.py
  dlrover/python/training_event/emitter.py
  dlrover/python/training_event/error_handler.py
  dlrover/python/training_event/event.py
  dlrover/python/training_event/exporter.py
  dlrover/python/training_event/predefined/__init__.py
  dlrover/python/training_event/predefined/_dlrover.py
  dlrover/python/training_event/predefined/common.py
  dlrover/python/training_event/predefined/trainer.py
  dlrover/trainer/torch/elastic_run.py
  docs/design/training-event.md
Labels: feature

#1464 optimize the shared lock
  dlrover/python/common/multi_process.py
  dlrover/python/tests/test_metric_monitor.py
  dlrover/python/tests/test_multi_process.py
Labels: enhancement

#1467 Further optimization implementation for the pre-check(diagnosis) process.
  dlrover/python/common/constants.py
  dlrover/python/common/global_context.py
  dlrover/python/common/node.py
  dlrover/python/common/storage.py
  dlrover/python/diagnosis/common/constants.py
  dlrover/python/diagnosis/common/diagnosis_action.py
  dlrover/python/elastic_agent/diagnosis/diagnosis_agent.py
  dlrover/python/elastic_agent/torch/training.py
  dlrover/python/master/args.py
  dlrover/python/master/diagnosis/diagnosis_manager.py
  dlrover/python/master/diagnosis/precheck_operator.py
  dlrover/python/master/dist_master.py
  dlrover/python/master/local_master.py
  dlrover/python/master/main.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/node/job_context.py
  dlrover/python/master/node/job_manager.py
  dlrover/python/tests/test_args.py
  dlrover/python/tests/test_diagnosis.py
  dlrover/python/tests/test_diagnosis_agent.py
  dlrover/python/tests/test_diagnosis_manager.py
  dlrover/python/tests/test_event_callback.py
  dlrover/python/tests/test_function_util.py
  dlrover/python/tests/test_global_context.py
  dlrover/python/tests/test_job_manager.py
  dlrover/python/tests/test_master.py
  dlrover/python/tests/test_pre_check_operator.py
  dlrover/python/util/function_util.py
  dlrover/python/util/time_util.py
  dlrover/trainer/torch/elastic_run.py
  docs/deployment/argument.md
  docs/design/training-pre-check.md
  docs/figures/pre_check_flow.png
  go/elasticjob/pkg/controllers/master/master.go
  go/elasticjob/pkg/controllers/master/master_test.go
Labels: enhancement, feature, waiting for pr merge

#1472 Several known issues fixed.
  dlrover/python/common/node.py
  dlrover/python/master/dist_master.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/servicer.py
  dlrover/python/tests/test_job_manager.py
  dlrover/python/tests/test_node.py
Labels: enhancement

#1477 Bugfix 20250224
  dlrover/python/master/local_master.py
  dlrover/python/master/watcher/k8s_watcher.py
  dlrover/python/tests/test_k8s_watcher.py
  dlrover/python/tests/test_master.py
  dlrover/python/tests/test_utils.py
  setup.py
Labels: bug

#1479 adjust xpu_type into job args
  dlrover/python/common/constants.py
  dlrover/python/common/global_context.py
  dlrover/python/common/metric/monitor.py
  dlrover/python/diagnosis/common/constants.py
  dlrover/python/master/diagnosis/diagnosis_manager.py
  dlrover/python/master/main.py
  dlrover/python/scheduler/job.py
  dlrover/python/tests/test_diagnosis_manager.py
  dlrover/python/tests/test_elastic_training_agent.py
  dlrover/python/tests/test_metric_monitor.py
Labels: enhancement

#1482 Level up unit test coverage.
  codecov.yml
Labels: dev issue
