Repository intelligent-machine-learning/dlrover, pull requests merged in 2025-07, with the labels that each got.

#1567 Feature: add 'Suspend' field for elasticjob. The master can be paused to prevent creating the workers.
  dlrover/python/common/constants.py
  dlrover/python/master/dist_master.py
  dlrover/python/master/node/job_context.py
  dlrover/python/master/scaler/pod_scaler.py
  dlrover/python/master/watcher/factory.py
  dlrover/python/master/watcher/k8s_watcher.py
  dlrover/python/scheduler/job.py
  dlrover/python/scheduler/kubernetes.py
  dlrover/python/tests/test_job_manager.py
  dlrover/python/tests/test_k8s_watcher.py
  go/elasticjob/api/v1alpha1/elasticjob_types.go
  go/elasticjob/config/crd/bases/elastic.iml.github.io_elasticjobs.yaml
  go/elasticjob/pkg/common/api/v1/types.go
  go/elasticjob/pkg/common/condition.go
  go/elasticjob/pkg/controllers/elasticjob_controller.go
Labels: feature

#1580 Known issue fixed.
  .github/actions/dlrover-python-test/action.yml
  .github/workflows/main.yml
  dlrover/python/elastic_agent/master_client.py
  dlrover/python/master/dist_master.py
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/shard/task_manager.py
  dlrover/python/tests/test_diagnosis_data_collector.py
  dlrover/python/tests/test_elastic_training_agent.py
  dlrover/python/tests/test_event_config.py
  dlrover/python/tests/test_master_client.py
  dlrover/python/tests/test_ray_job_args.py
  dlrover/python/tests/test_task_manager.py
  dlrover/python/tests/test_utils.py
  dlrover/trainer/tests/torch/elastic_run_test.py
  dlrover/trainer/torch/elastic_run.py
  scripts/ci_install.sh
Labels: enhancement

#1579 Refactor unified API.
  dlrover/python/unified/api/base.py
  dlrover/python/unified/api/rl.py
  dlrover/python/unified/tests/api/test_api.py
  dlrover/python/unified/tests/integration_test.py
  dlrover/python/unified/trainer/example/rl/openrlhf/ppo/main.py
  dlrover/python/unified/trainer/example/rl/verl/ppo/main.py
  docs/tutorial/unified/unified_api_guide.md
Labels: enhancement

#1583 Create publish_pypi.yml
  .github/workflows/publish_pypi.yml
  setup.py
Labels: dev issue

#1584 Fix publish pypi using.
  .github/workflows/publish_pypi.yml
Labels: dev issue

#1586 Redefine deps.
  README.md
  dlrover/python/elastic_agent/master_client.py
  dlrover/python/master/servicer.py
  dlrover/python/tests/test_master_client.py
  dlrover/python/tests/test_servicer.py
  dlrover/python/unified/trainer/elastic_workload.py
  docs/blogs/flash_checkpoint.md
  docs/blogs/flash_checkpoint_cn.md
  docs/blogs/megatron_flash_checkpoint.md
  docs/blogs/megatron_flash_checkpoint_cn.md
  docs/blogs/stabilize_llm_training_cn.md
  docs/tutorial/elastic_torch_training.md
  examples/pytorch/fcp_demo.py
  setup.py
Labels: enhancement

#1591 Fix tornado importing in servicer.
  dlrover/python/master/servicer.py
  dlrover/python/tests/test_master_client.py
  dlrover/python/tests/test_servicer.py
Labels: bug

#1595 Add' all workers succeeded exited' judgement.
  dlrover/python/master/node/worker.py
  dlrover/python/tests/test_worker_manager.py
Labels: enhancement

#1599 Fix pending worker ret issue.
  dlrover/python/master/node/dist_job_manager.py
  dlrover/python/master/node/ps.py
  dlrover/python/master/node/training_node.py
  dlrover/python/master/node/worker.py
  dlrover/python/tests/test_job_manager.py
  dlrover/python/tests/test_ps_manager.py
  dlrover/python/tests/test_worker_manager.py
Labels: bug
